http:
  routers:
    dashboard:
      rule: 'Host(`dashboard.localhost`)'
      entrypoints:
        - https
      tls: {}
      service: api@internal

    dashboard-http2https:
      rule: 'Host(`dashboard.localhost`)'
      middlewares:
        - https_redirect
      service: api@internal

    demotraefik:
      rule: 'Host(`demotraefik.localhost`)'
      entrypoints:
        - https
      tls: {}
      service: demotraefik

    demotraefik-http2https:
      rule: 'Host(`demotraefik.localhost`)'
      middlewares:
        - https_redirect
      service: api@internal

  middlewares:
    https_redirect:
      redirectscheme:
        scheme: https
        permanent: true

  services:
    demotraefik:
      loadBalancer:
        servers:
          - url: 'http://whoami'
